import { createSlice } from "@reduxjs/toolkit";

// Create a slice of Redux state for managing city-related data
const cityDataSlice = createSlice({
  // Define the name of the slice
  name: "cityData",
  // Define the initial state of the slice
  initialState: {
    // Define initial values for data, forecast5Days, and currentWeather
    data: [], // Array to hold city data
    forecast5Days: null, // Holds 5-day forecast data
    currentWeather: null, // Holds current weather data
  },
  // Define reducer functions to update the slice's state
  reducers: {
    // Reducer function to update the city data state
    updateCityData: (state, action) => {
      // Update the city data state with the payload value
      state.data = action.payload;
    },

    // Reducer function to update the 5-day forecast state
    update5DaysForecast: (state, action) => {
      // Update the 5-day forecast state with the payload value
      state.forecast5Days = action.payload;
    },

    // Reducer function to update the current weather state
    updateCurrentWeather: (state, action) => {
      // Update the current weather state with the payload value
      state.currentWeather = action.payload;
    },
  },
});

// Extract and export the action creators from the cityDataSlice
export const { updateCityData, update5DaysForecast, updateCurrentWeather } =
  cityDataSlice.actions;

// Export the reducer function generated by createSlice
export default cityDataSlice.reducer;
