// searchSlice.js
import { createSlice } from "@reduxjs/toolkit";

// Created a slice of Redux state for managing search-related data
const searchSlice = createSlice({
  // Define the name of the slice
  name: "search",
  // Define the initial state of the slice
  initialState: {
    // Define initial values for query and filteredResults
    query: "",
    filteredResults: [],
  },
  // Define reducer functions to update the slice's state
  reducers: {
    // Reducer function to update the query state
    updateQuery: (state, action) => {
      // Update the query state with the payload value
      state.query = action.payload;
    },
    // Reducer function to update the filteredResults state
    updateFilteredResults: (state, action) => {
      // Update the filteredResults state with the payload value
      state.filteredResults = action.payload;
    },
  },
});

// Extract and export the action creators from the searchSlice
export const { updateQuery, updateFilteredResults } = searchSlice.actions;

// Export the reducer function generated by createSlice
export default searchSlice.reducer;
